server:
  port: 8090
spring:
  application:
    name: alnilam
  datasource:
    url: jdbc:mysql://192.168.2.40:3306/alnilam?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 300000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: pres.jeremy.alnilam.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: false
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: debug